# Site settings
title: Evironmental Fluid Mechanics Lab UKZN
description: Passionate about all things fluids.
cover: assets/images/river.svg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://efml.github.io/efml-live/" # the base hostname & protocol for your site
paginate: 5 #The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: efml_ukzn
github:  EFML

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username:  EFML #github username
repo: efml #github repository
branch: master #branch
relative_source: ../efml/ #source directory
destination: ../efml-pages/ #destination directory
production_url:  https://efml.github.io/efml-live/
source_url:  https://github.com/efml/efml-live #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
